#!/usr/bin/env python3
"""Generate seed_patterns.jsonl for EntityRuler NER system.

Sources: TIOBE, GitHub Linguist, npm/PyPI top packages, DB-Engines,
awesome-lists, cloud provider docs, HuggingFace trending, etc.

Target: 800-1200 deduplicated entries across 10 categories.
"""

import json
import sys
from collections import OrderedDict

# ---------------------------------------------------------------------------
# Data structures: (name, [aliases...])
# Each category is a list of tuples: ("PrimaryName", ["alias1", "alias2"])
# Aliases become separate JSONL entries with the same label.
# ---------------------------------------------------------------------------

LANGUAGES = [
    # TIOBE top 50 + GitHub Linguist canonical + aliases
    ("Python", []),
    ("JavaScript", ["JS"]),
    ("TypeScript", ["TS"]),
    ("Java", []),
    ("C", []),
    ("C++", ["CPP", "Cpp"]),
    ("C#", ["C Sharp", "CSharp"]),
    ("Go", ["Golang"]),
    ("Rust", []),
    ("Swift", []),
    ("Kotlin", []),
    ("Ruby", []),
    ("PHP", []),
    ("Scala", []),
    ("Perl", []),
    ("R", []),
    ("MATLAB", []),
    ("Lua", []),
    ("Dart", []),
    ("Elixir", []),
    ("Haskell", []),
    ("Clojure", []),
    ("Erlang", []),
    ("Julia", []),
    ("Zig", []),
    ("Nim", []),
    ("Crystal", []),
    ("OCaml", []),
    ("F#", ["FSharp", "F Sharp"]),
    ("Fortran", []),
    ("COBOL", []),
    ("Assembly", ["ASM"]),
    ("Objective-C", ["ObjC"]),
    ("Visual Basic", ["VB", "VB.NET"]),
    ("Groovy", []),
    ("PowerShell", []),
    ("Bash", ["Shell"]),
    ("Zsh", []),
    ("SQL", []),
    ("PL/SQL", []),
    ("T-SQL", ["Transact-SQL"]),
    ("HTML", []),
    ("CSS", []),
    ("SCSS", ["Sass"]),
    ("Less", []),
    ("Solidity", []),
    ("Vyper", []),
    ("YAML", ["YML"]),
    ("JSON", []),
    ("TOML", []),
    ("XML", []),
    ("GraphQL", ["GQL"]),
    ("Protobuf", ["Protocol Buffers"]),
    ("Terraform", ["HCL"]),
    ("Mojo", []),
    ("Roc", []),
    ("V", ["Vlang"]),
    ("Ada", []),
    ("Pascal", []),
    ("Delphi", []),
    ("Prolog", []),
    ("Lisp", []),
    ("Common Lisp", []),
    ("Scheme", []),
    ("Racket", []),
    ("Smalltalk", []),
    ("D", ["Dlang"]),
    ("Apex", []),
    ("ABAP", []),
    ("Verilog", []),
    ("VHDL", []),
    ("SystemVerilog", []),
    ("WebAssembly", ["WASM", "Wasm"]),
    ("CoffeeScript", []),
    ("ReasonML", []),
    ("Elm", []),
    ("PureScript", []),
    ("Idris", []),
    ("Agda", []),
    ("Coq", []),
    ("Lean", []),
    ("CUDA", []),
    ("OpenCL", []),
]

FRAMEWORKS = [
    # Web frameworks
    ("React", ["ReactJS", "React.js"]),
    ("Next.js", ["NextJS", "Next"]),
    ("Vue", ["Vue.js", "VueJS"]),
    ("Nuxt", ["Nuxt.js", "NuxtJS"]),
    ("Angular", ["AngularJS"]),
    ("Svelte", []),
    ("SvelteKit", []),
    ("Solid", ["SolidJS", "Solid.js"]),
    ("Astro", []),
    ("Remix", []),
    ("Gatsby", ["GatsbyJS"]),
    ("Express", ["Express.js", "ExpressJS"]),
    ("Fastify", []),
    ("Koa", ["Koa.js"]),
    ("Hono", []),
    ("Nest.js", ["NestJS"]),
    ("Django", []),
    ("Flask", []),
    ("FastAPI", []),
    ("Starlette", []),
    ("Litestar", []),
    ("Tornado", []),
    ("Sanic", []),
    ("Rails", ["Ruby on Rails", "RoR"]),
    ("Sinatra", []),
    ("Spring", ["Spring Boot", "SpringBoot"]),
    ("Quarkus", []),
    ("Micronaut", []),
    ("Laravel", []),
    ("Symfony", []),
    ("Gin", []),
    ("Echo", []),
    ("Fiber", []),
    ("Chi", []),
    ("Actix", ["Actix Web"]),
    ("Axum", []),
    ("Rocket", []),
    ("Phoenix", []),
    ("ASP.NET", ["ASP.NET Core"]),
    ("Blazor", []),
    ("htmx", ["HTMX"]),
    # Mobile
    ("React Native", []),
    ("Flutter", []),
    ("SwiftUI", []),
    ("Jetpack Compose", []),
    ("Expo", []),
    ("Ionic", []),
    ("Capacitor", []),
    # CSS / UI
    ("Tailwind CSS", ["Tailwind", "TailwindCSS"]),
    ("Bootstrap", []),
    ("Bulma", []),
    ("Material UI", ["MUI"]),
    ("Chakra UI", ["Chakra"]),
    ("Ant Design", ["AntD"]),
    ("shadcn/ui", ["shadcn"]),
    ("Radix", ["Radix UI"]),
    ("Headless UI", []),
    ("DaisyUI", []),
    # ML / Data
    ("TensorFlow", ["TF"]),
    ("PyTorch", []),
    ("JAX", []),
    ("Keras", []),
    ("scikit-learn", ["sklearn"]),
    ("XGBoost", []),
    ("LightGBM", []),
    ("CatBoost", []),
    ("Hugging Face Transformers", ["Transformers"]),
    ("LangChain", []),
    ("LlamaIndex", []),
    ("DSPy", []),
    ("spaCy", []),
    ("NLTK", []),
    ("pandas", []),
    ("NumPy", []),
    ("SciPy", []),
    ("Matplotlib", []),
    ("Plotly", []),
    ("Seaborn", []),
    ("Polars", []),
    ("DuckDB", []),
    ("Apache Spark", ["Spark", "PySpark"]),
    ("Apache Flink", ["Flink"]),
    ("Apache Kafka", ["Kafka"]),
    ("Apache Airflow", ["Airflow"]),
    ("Prefect", []),
    ("Dagster", []),
    ("MLflow", []),
    ("Weights & Biases", ["W&B", "WandB"]),
    ("Ray", []),
    ("Dask", []),
    ("Celery", []),
    # Testing
    ("Jest", []),
    ("Vitest", []),
    ("Mocha", []),
    ("Cypress", []),
    ("Playwright", []),
    ("Selenium", []),
    ("Puppeteer", []),
    ("pytest", []),
    ("unittest", []),
    ("JUnit", []),
    ("TestNG", []),
    ("RSpec", []),
    # Build / Bundlers
    ("Vite", []),
    ("Webpack", []),
    ("esbuild", []),
    ("Rollup", []),
    ("Turbopack", []),
    ("Parcel", []),
    ("Bun", []),
    # State management
    ("Redux", []),
    ("Zustand", []),
    ("MobX", []),
    ("Jotai", []),
    ("Recoil", []),
    ("XState", []),
    ("TanStack Query", ["React Query"]),
    ("SWR", []),
    # ORM / DB libraries
    ("Prisma", []),
    ("Drizzle", ["Drizzle ORM"]),
    ("SQLAlchemy", []),
    ("TypeORM", []),
    ("Sequelize", []),
    ("Mongoose", []),
    ("Knex", ["Knex.js"]),
    ("Alembic", []),
    # Other
    ("Electron", []),
    ("Tauri", []),
    ("Qt", []),
    ("GTK", []),
    ("OpenCV", []),
    ("Three.js", ["ThreeJS"]),
    ("D3.js", ["D3"]),
    ("Socket.IO", []),
    ("tRPC", []),
    ("gRPC", []),
    ("Protobuf", []),
]

DATABASES = [
    # DB-Engines top 50 + aliases
    ("PostgreSQL", ["Postgres"]),
    ("MySQL", []),
    ("MariaDB", []),
    ("SQLite", []),
    ("Oracle Database", ["Oracle DB", "Oracle"]),
    ("Microsoft SQL Server", ["MSSQL", "SQL Server"]),
    ("MongoDB", ["Mongo"]),
    ("Redis", []),
    ("Elasticsearch", ["ES", "Elastic"]),
    ("DynamoDB", ["Amazon DynamoDB"]),
    ("Cassandra", ["Apache Cassandra"]),
    ("CockroachDB", []),
    ("TiDB", []),
    ("Vitess", []),
    ("PlanetScale", []),
    ("Supabase", []),
    ("Neon", []),
    ("Neo4j", []),
    ("FalkorDB", []),
    ("ArangoDB", []),
    ("Amazon Neptune", ["Neptune"]),
    ("ClickHouse", []),
    ("Apache Druid", ["Druid"]),
    ("TimescaleDB", []),
    ("InfluxDB", []),
    ("Prometheus", []),
    ("Pinecone", []),
    ("Weaviate", []),
    ("Milvus", []),
    ("Qdrant", []),
    ("ChromaDB", ["Chroma"]),
    ("pgvector", []),
    ("Couchbase", []),
    ("CouchDB", ["Apache CouchDB"]),
    ("RethinkDB", []),
    ("ScyllaDB", []),
    ("Memcached", []),
    ("Valkey", []),
    ("etcd", []),
    ("FoundationDB", []),
    ("YugabyteDB", []),
    ("Firestore", ["Cloud Firestore"]),
    ("Firebase Realtime Database", ["Firebase RTDB"]),
    ("Amazon RDS", ["RDS"]),
    ("Amazon Aurora", ["Aurora"]),
    ("Amazon Redshift", ["Redshift"]),
    ("Google BigQuery", ["BigQuery"]),
    ("Snowflake", []),
    ("Databricks", []),
    ("Apache HBase", ["HBase"]),
    ("Apache Hive", ["Hive"]),
    ("Dolt", []),
    ("SurrealDB", []),
    ("EdgeDB", []),
    ("LanceDB", []),
    ("Turso", []),
    ("libSQL", []),
]

TOOLS = [
    # Package managers
    ("npm", []),
    ("pnpm", []),
    ("Yarn", []),
    ("pip", []),
    ("uv", []),
    ("Poetry", []),
    ("Conda", []),
    ("Homebrew", ["brew"]),
    ("apt", ["apt-get"]),
    ("Cargo", []),
    ("Maven", []),
    ("Gradle", []),
    ("NuGet", []),
    ("Composer", []),
    ("CocoaPods", []),
    ("RubyGems", ["gem"]),
    # Build / CI / CD
    ("Make", ["GNU Make"]),
    ("CMake", []),
    ("Bazel", []),
    ("Ninja", []),
    ("Docker", []),
    ("Docker Compose", []),
    ("Podman", []),
    ("Kubernetes", ["K8s", "k8s"]),
    ("Helm", []),
    ("Terraform", []),
    ("Pulumi", []),
    ("Ansible", []),
    ("Chef", []),
    ("Puppet", []),
    ("Vagrant", []),
    ("GitHub Actions", ["GHA"]),
    ("GitLab CI", ["GitLab CI/CD"]),
    ("Jenkins", []),
    ("CircleCI", []),
    ("Travis CI", []),
    ("Buildkite", []),
    ("Argo CD", ["ArgoCD"]),
    ("Flux", []),
    ("Tekton", []),
    ("Dagger", []),
    # Linters / Formatters
    ("ESLint", []),
    ("Prettier", []),
    ("Biome", []),
    ("Ruff", []),
    ("Black", []),
    ("Flake8", []),
    ("mypy", []),
    ("Pyright", []),
    ("RuboCop", []),
    ("Clippy", []),
    ("golangci-lint", []),
    ("ShellCheck", []),
    ("hadolint", []),
    ("oxlint", []),
    # Editors / IDEs
    ("Visual Studio Code", ["VS Code", "VSCode"]),
    ("Neovim", ["nvim"]),
    ("Vim", []),
    ("Emacs", []),
    ("IntelliJ IDEA", ["IntelliJ"]),
    ("PyCharm", []),
    ("WebStorm", []),
    ("Xcode", []),
    ("Android Studio", []),
    ("Zed", []),
    ("Cursor", []),
    ("Windsurf", []),
    # CLI tools
    ("Git", []),
    ("GitHub CLI", ["gh"]),
    ("curl", []),
    ("wget", []),
    ("jq", []),
    ("ripgrep", ["rg"]),
    ("fd", []),
    ("fzf", []),
    ("tmux", []),
    ("Zellij", []),
    ("htop", []),
    ("Nix", []),
    ("direnv", []),
    ("asdf", []),
    ("mise", []),
    ("fnm", []),
    ("nvm", []),
    ("pyenv", []),
    ("nodemon", []),
    ("PM2", []),
    ("Supervisor", []),
    ("systemd", []),
    ("Nginx", []),
    ("Caddy", []),
    ("Apache HTTP Server", ["httpd"]),
    ("HAProxy", []),
    ("Traefik", []),
    ("Envoy", []),
    ("Istio", []),
    ("Linkerd", []),
    # Observability
    ("Grafana", []),
    ("Loki", []),
    ("Jaeger", []),
    ("OpenTelemetry", ["OTel"]),
    ("Zipkin", []),
    # Security
    ("Vault", ["HashiCorp Vault"]),
    ("Trivy", []),
    ("Snyk", []),
    ("SonarQube", []),
    ("Dependabot", []),
    ("Renovate", []),
]

PLATFORMS = [
    # Cloud providers
    ("AWS", ["Amazon Web Services"]),
    ("Google Cloud", ["GCP", "Google Cloud Platform"]),
    ("Microsoft Azure", ["Azure"]),
    ("DigitalOcean", []),
    ("Linode", ["Akamai Cloud"]),
    ("Hetzner", ["Hetzner Cloud"]),
    ("Oracle Cloud", ["OCI"]),
    ("IBM Cloud", []),
    ("Alibaba Cloud", ["Aliyun"]),
    # AWS services (top 30)
    ("Amazon EC2", ["EC2"]),
    ("Amazon S3", ["S3"]),
    ("AWS Lambda", ["Lambda"]),
    ("Amazon ECS", ["ECS"]),
    ("Amazon EKS", ["EKS"]),
    ("AWS Fargate", ["Fargate"]),
    ("Amazon SQS", ["SQS"]),
    ("Amazon SNS", ["SNS"]),
    ("Amazon CloudFront", ["CloudFront"]),
    ("AWS IAM", ["IAM"]),
    ("Amazon VPC", ["VPC"]),
    ("AWS CloudFormation", ["CloudFormation"]),
    ("Amazon Route 53", ["Route 53"]),
    ("Amazon ElastiCache", ["ElastiCache"]),
    ("AWS Step Functions", ["Step Functions"]),
    ("Amazon EventBridge", ["EventBridge"]),
    ("AWS Cognito", ["Cognito"]),
    ("Amazon Kinesis", ["Kinesis"]),
    ("AWS Secrets Manager", []),
    ("Amazon SageMaker", ["SageMaker"]),
    ("AWS Bedrock", ["Bedrock"]),
    ("Amazon ECR", ["ECR"]),
    # GCP services
    ("Google Cloud Run", ["Cloud Run"]),
    ("Google Cloud Functions", ["Cloud Functions"]),
    ("Google Cloud Storage", ["GCS"]),
    ("Google Compute Engine", ["GCE"]),
    ("Google Kubernetes Engine", ["GKE"]),
    ("Google Cloud Pub/Sub", ["Pub/Sub"]),
    ("Google Cloud SQL", ["Cloud SQL"]),
    ("Google Cloud Spanner", ["Spanner"]),
    ("Vertex AI", []),
    ("Google Cloud CDN", []),
    # Azure services
    ("Azure Functions", []),
    ("Azure App Service", []),
    ("Azure Blob Storage", []),
    ("Azure Kubernetes Service", ["AKS"]),
    ("Azure DevOps", []),
    ("Azure Cosmos DB", ["Cosmos DB"]),
    ("Azure OpenAI Service", []),
    ("Azure Container Apps", []),
    # Hosting / PaaS
    ("Vercel", []),
    ("Netlify", []),
    ("Cloudflare", ["Cloudflare Workers"]),
    ("Railway", []),
    ("Render", []),
    ("Fly.io", ["Fly"]),
    ("Heroku", []),
    ("Deno Deploy", []),
    ("Coolify", []),
    # DevOps platforms
    ("GitHub", []),
    ("GitLab", []),
    ("Bitbucket", []),
    ("Gitea", []),
    ("Docker Hub", []),
    ("npm Registry", []),
    ("PyPI", []),
    ("crates.io", []),
    # Container / Orchestration
    ("Amazon ECS", []),
    ("Google Cloud Run", []),
    ("Nomad", ["HashiCorp Nomad"]),
]

AI_MODELS = [
    # Claude family
    ("Claude", []),
    ("Claude 3.5 Sonnet", []),
    ("Claude 3.5 Haiku", []),
    ("Claude 3 Opus", []),
    ("Claude 3 Sonnet", []),
    ("Claude 3 Haiku", []),
    ("Claude 4 Opus", []),
    ("Claude 4 Sonnet", []),
    # GPT family
    ("GPT-4o", []),
    ("GPT-4o mini", []),
    ("GPT-4 Turbo", []),
    ("GPT-4", []),
    ("GPT-3.5 Turbo", ["GPT-3.5"]),
    ("o1", []),
    ("o1-mini", []),
    ("o1-pro", []),
    ("o3", []),
    ("o3-mini", []),
    ("o4-mini", []),
    ("GPT-4.1", []),
    ("GPT-4.1 mini", []),
    ("GPT-4.1 nano", []),
    # Gemini family
    ("Gemini", []),
    ("Gemini 2.0 Flash", []),
    ("Gemini 2.0 Pro", []),
    ("Gemini 1.5 Pro", []),
    ("Gemini 1.5 Flash", []),
    ("Gemma", []),
    ("Gemma 2", []),
    ("Gemma 3", []),
    # Llama family
    ("Llama", []),
    ("Llama 3", []),
    ("Llama 3.1", []),
    ("Llama 3.2", []),
    ("Llama 3.3", []),
    ("Llama 4", []),
    ("Llama 4 Scout", []),
    ("Llama 4 Maverick", []),
    ("CodeLlama", ["Code Llama"]),
    # Mistral family
    ("Mistral", []),
    ("Mistral Large", []),
    ("Mistral Medium", []),
    ("Mistral Small", []),
    ("Mixtral", []),
    ("Mixtral 8x7B", []),
    ("Mixtral 8x22B", []),
    ("Codestral", []),
    ("Pixtral", []),
    # Cohere
    ("Cohere Command", ["Command R", "Command R+"]),
    ("Cohere Embed", []),
    ("Cohere Rerank", []),
    # Open models
    ("Phi-3", []),
    ("Phi-4", []),
    ("Qwen", []),
    ("Qwen 2.5", []),
    ("DeepSeek", []),
    ("DeepSeek V3", []),
    ("DeepSeek R1", []),
    ("DeepSeek Coder", []),
    ("Yi", []),
    ("Falcon", []),
    ("BLOOM", []),
    ("Stable Diffusion", []),
    ("SDXL", []),
    ("DALL-E", ["DALL-E 3"]),
    ("Midjourney", []),
    ("Whisper", []),
    ("Suno", []),
    # Embedding models
    ("text-embedding-3-small", []),
    ("text-embedding-3-large", []),
    ("text-embedding-ada-002", []),
    ("Voyage", ["Voyage AI"]),
    ("Nomic Embed", []),
    ("BGE", []),
    ("E5", []),
    ("GTE", []),
    # Coding assistants (model-adjacent)
    ("GitHub Copilot", ["Copilot"]),
    ("Claude Code", []),
    ("Cursor AI", []),
    ("Cody", ["Sourcegraph Cody"]),
    ("Codex", ["OpenAI Codex"]),
    ("AlphaCode", []),
    ("StarCoder", ["StarCoder2"]),
    ("WizardCoder", []),
]

ORGANIZATIONS = [
    # Big tech
    ("Google", ["Alphabet"]),
    ("Microsoft", []),
    ("Apple", []),
    ("Amazon", []),
    ("Meta", ["Facebook"]),
    ("Netflix", []),
    ("Nvidia", ["NVIDIA"]),
    ("Intel", []),
    ("AMD", []),
    ("Qualcomm", []),
    ("Samsung", []),
    ("IBM", []),
    ("Oracle", []),
    ("Salesforce", []),
    ("Adobe", []),
    ("Spotify", []),
    ("Uber", []),
    ("Airbnb", []),
    ("Twitter", ["X"]),
    ("LinkedIn", []),
    ("Snap", ["Snapchat"]),
    ("Pinterest", []),
    ("Shopify", []),
    ("Square", ["Block"]),
    ("Palantir", []),
    # AI Labs
    ("Anthropic", []),
    ("OpenAI", []),
    ("DeepMind", ["Google DeepMind"]),
    ("Mistral AI", []),
    ("Cohere", []),
    ("Stability AI", []),
    ("Hugging Face", ["HuggingFace"]),
    ("Runway", []),
    ("Midjourney", []),
    ("xAI", []),
    ("Inflection AI", []),
    ("Adept AI", []),
    ("Character AI", []),
    ("Perplexity", ["Perplexity AI"]),
    ("Together AI", []),
    ("Groq", []),
    ("Cerebras", []),
    ("Anyscale", []),
    ("Modal", []),
    ("Replicate", []),
    # Developer companies
    ("HashiCorp", []),
    ("Elastic", []),
    ("Confluent", []),
    ("MongoDB Inc", []),
    ("Cloudflare", []),
    ("Datadog", []),
    ("Twilio", []),
    ("Stripe", []),
    ("Vercel", []),
    ("Supabase", []),
    ("PlanetScale", []),
    ("Neon", []),
    ("Fly.io", []),
    ("Railway", []),
    ("GitLab", []),
    ("JetBrains", []),
    ("Atlassian", []),
    ("Canonical", []),
    ("Red Hat", []),
    ("SUSE", []),
    ("Grafana Labs", []),
    ("Kong", []),
    ("Snyk", []),
    ("LaunchDarkly", []),
    ("PostHog", []),
    # Foundations
    ("Linux Foundation", []),
    ("Apache Software Foundation", ["Apache Foundation", "ASF"]),
    ("CNCF", ["Cloud Native Computing Foundation"]),
    ("OpenJS Foundation", []),
    ("Python Software Foundation", ["PSF"]),
    ("Rust Foundation", []),
    ("Eclipse Foundation", []),
]

SERVICES = [
    # Auth
    ("Auth0", []),
    ("Clerk", []),
    ("Okta", []),
    ("Firebase Auth", []),
    ("Supabase Auth", []),
    ("FusionAuth", []),
    ("Keycloak", []),
    ("WorkOS", []),
    ("Stytch", []),
    # Payments
    ("Stripe", []),
    ("Plaid", []),
    ("Square", []),
    ("Braintree", []),
    ("Adyen", []),
    ("PayPal", []),
    ("Paddle", []),
    ("LemonSqueezy", ["Lemon Squeezy"]),
    # Email / Messaging
    ("SendGrid", []),
    ("Postmark", []),
    ("Mailgun", []),
    ("Amazon SES", ["SES"]),
    ("Resend", []),
    ("Twilio", []),
    ("MessageBird", []),
    # Monitoring / Observability
    ("Datadog", []),
    ("New Relic", []),
    ("PagerDuty", []),
    ("Sentry", []),
    ("LogRocket", []),
    ("Honeycomb", []),
    ("Axiom", []),
    ("BetterStack", ["Better Stack"]),
    ("Checkly", []),
    # Analytics
    ("Segment", []),
    ("Mixpanel", []),
    ("Amplitude", []),
    ("PostHog", []),
    ("Google Analytics", ["GA4"]),
    ("Plausible", []),
    ("Heap", []),
    # CMS / Content
    ("Contentful", []),
    ("Sanity", []),
    ("Strapi", []),
    ("Directus", []),
    ("Payload CMS", ["Payload"]),
    ("WordPress", []),
    ("Ghost", []),
    # Feature flags / Config
    ("LaunchDarkly", []),
    ("Unleash", []),
    ("ConfigCat", []),
    ("Split", []),
    ("Statsig", []),
    # Search
    ("Algolia", []),
    ("Typesense", []),
    ("Meilisearch", []),
    # File storage / CDN
    ("Cloudinary", []),
    ("Imgix", []),
    ("Uploadthing", []),
    ("Fastly", []),
    ("Akamai", []),
    ("Bunny CDN", []),
    # Misc SaaS
    ("Notion", []),
    ("Slack", []),
    ("Discord", []),
    ("Linear", []),
    ("Jira", []),
    ("Confluence", []),
    ("Figma", []),
    ("Retool", []),
    ("Supabase", []),
    ("Neon", []),
    ("Upstash", []),
    ("Convex", []),
]

PROTOCOLS = [
    # Network
    ("HTTP", []),
    ("HTTPS", []),
    ("HTTP/2", ["H2"]),
    ("HTTP/3", ["H3", "QUIC"]),
    ("WebSocket", ["WebSockets", "WS"]),
    ("Server-Sent Events", ["SSE"]),
    ("gRPC", []),
    ("REST", ["RESTful"]),
    ("GraphQL", []),
    ("SOAP", []),
    ("TCP", []),
    ("UDP", []),
    ("DNS", []),
    ("FTP", ["SFTP"]),
    ("SSH", []),
    ("SMTP", []),
    ("IMAP", []),
    ("MQTT", []),
    ("AMQP", []),
    ("NATS", []),
    ("ZeroMQ", ["ZMQ", "0MQ"]),
    ("RSocket", []),
    # Auth / Security
    ("OAuth 2.0", ["OAuth2", "OAuth"]),
    ("OpenID Connect", ["OIDC"]),
    ("SAML", []),
    ("JWT", ["JSON Web Token"]),
    ("JWE", []),
    ("PKCE", []),
    ("SCIM", []),
    ("LDAP", []),
    ("Kerberos", []),
    ("TLS", ["TLS 1.3"]),
    ("mTLS", ["mutual TLS"]),
    ("SSL", []),
    ("CORS", []),
    ("CSP", ["Content Security Policy"]),
    # Data / Serialization
    ("JSON-RPC", []),
    ("XML-RPC", []),
    ("MessagePack", ["msgpack"]),
    ("Avro", []),
    ("Thrift", []),
    ("Cap'n Proto", []),
    ("FlatBuffers", []),
    ("CBOR", []),
    ("BSON", []),
    # Consensus / Distributed
    ("Raft", []),
    ("Paxos", []),
    ("CRDT", ["CRDTs"]),
    ("Gossip Protocol", []),
    ("Two-Phase Commit", ["2PC"]),
    # API specs
    ("OpenAPI", ["Swagger"]),
    ("AsyncAPI", []),
    ("JSON Schema", []),
    ("JSON-LD", []),
    ("OData", []),
    ("Webhooks", []),
]

CONCEPTS = [
    # Design patterns (GoF + modern)
    ("Singleton", ["Singleton Pattern"]),
    ("Factory", ["Factory Pattern", "Factory Method"]),
    ("Abstract Factory", []),
    ("Builder", ["Builder Pattern"]),
    ("Prototype", ["Prototype Pattern"]),
    ("Adapter", ["Adapter Pattern"]),
    ("Decorator", ["Decorator Pattern"]),
    ("Observer", ["Observer Pattern"]),
    ("Strategy", ["Strategy Pattern"]),
    ("Command", ["Command Pattern"]),
    ("Iterator", ["Iterator Pattern"]),
    ("State", ["State Pattern"]),
    ("Proxy", ["Proxy Pattern"]),
    ("Facade", ["Facade Pattern"]),
    ("Mediator", ["Mediator Pattern"]),
    ("Chain of Responsibility", []),
    ("Template Method", []),
    ("Visitor", ["Visitor Pattern"]),
    ("Flyweight", ["Flyweight Pattern"]),
    ("Composite", ["Composite Pattern"]),
    ("Bridge", ["Bridge Pattern"]),
    ("Repository Pattern", []),
    ("Unit of Work", []),
    ("Dependency Injection", ["DI"]),
    ("Inversion of Control", ["IoC"]),
    # Architecture patterns
    ("Microservices", ["Microservice"]),
    ("Monolith", ["Monolithic"]),
    ("Modular Monolith", []),
    ("Service-Oriented Architecture", ["SOA"]),
    ("Event-Driven Architecture", ["EDA"]),
    ("CQRS", ["Command Query Responsibility Segregation"]),
    ("Event Sourcing", []),
    ("Domain-Driven Design", ["DDD"]),
    ("Hexagonal Architecture", ["Ports and Adapters"]),
    ("Clean Architecture", []),
    ("Layered Architecture", []),
    ("Serverless", ["Serverless Architecture"]),
    ("Jamstack", ["JAMstack"]),
    ("Micro Frontends", ["Micro Frontend"]),
    ("Backend for Frontend", ["BFF"]),
    ("API Gateway", []),
    ("Service Mesh", []),
    ("Sidecar Pattern", []),
    ("Strangler Fig", ["Strangler Fig Pattern"]),
    ("Saga Pattern", ["Saga"]),
    ("Outbox Pattern", []),
    ("Circuit Breaker", ["Circuit Breaker Pattern"]),
    ("Bulkhead", ["Bulkhead Pattern"]),
    ("Retry Pattern", []),
    ("Backpressure", []),
    ("Rate Limiting", []),
    ("Load Balancing", []),
    # Distributed systems (DDIA)
    ("CAP Theorem", ["CAP"]),
    ("ACID", []),
    ("BASE", []),
    ("Eventual Consistency", []),
    ("Strong Consistency", []),
    ("Linearizability", []),
    ("Serializability", []),
    ("Idempotency", ["Idempotent"]),
    ("Sharding", ["Horizontal Partitioning"]),
    ("Replication", []),
    ("Leader Election", []),
    ("Consensus", []),
    ("Vector Clock", ["Vector Clocks"]),
    ("Bloom Filter", []),
    ("Consistent Hashing", []),
    ("Write-Ahead Log", ["WAL"]),
    ("LSM Tree", ["Log-Structured Merge Tree"]),
    ("B-Tree", ["B+ Tree"]),
    ("Merkle Tree", []),
    # Software engineering concepts
    ("CI/CD", ["Continuous Integration", "Continuous Deployment"]),
    ("Infrastructure as Code", ["IaC"]),
    ("GitOps", []),
    ("DevOps", []),
    ("SRE", ["Site Reliability Engineering"]),
    ("Platform Engineering", []),
    ("Trunk-Based Development", []),
    ("Feature Flags", ["Feature Toggles"]),
    ("Blue-Green Deployment", []),
    ("Canary Deployment", ["Canary Release"]),
    ("Rolling Deployment", []),
    ("A/B Testing", []),
    ("Chaos Engineering", []),
    ("Observability", []),
    ("Three Pillars of Observability", []),
    ("SLI", ["Service Level Indicator"]),
    ("SLO", ["Service Level Objective"]),
    ("SLA", ["Service Level Agreement"]),
    ("Twelve-Factor App", ["12-Factor"]),
    ("SOLID Principles", ["SOLID"]),
    ("DRY", ["Don't Repeat Yourself"]),
    ("KISS", ["Keep It Simple"]),
    ("YAGNI", ["You Aren't Gonna Need It"]),
    ("TDD", ["Test-Driven Development"]),
    ("BDD", ["Behavior-Driven Development"]),
    ("Pair Programming", []),
    ("Code Review", []),
    ("Technical Debt", ["Tech Debt"]),
    ("Refactoring", []),
    ("Semantic Versioning", ["SemVer"]),
    ("Monorepo", []),
    ("Polyrepo", []),
    # Data concepts
    ("ETL", ["Extract Transform Load"]),
    ("ELT", []),
    ("Data Lake", []),
    ("Data Warehouse", []),
    ("Data Mesh", []),
    ("Data Pipeline", []),
    ("Streaming", ["Stream Processing"]),
    ("Batch Processing", []),
    ("MapReduce", []),
    ("Materialized View", []),
    ("Change Data Capture", ["CDC"]),
    # ML / AI concepts
    ("RAG", ["Retrieval Augmented Generation"]),
    ("Fine-tuning", ["Fine Tuning"]),
    ("Prompt Engineering", []),
    ("Few-Shot Learning", ["Few-Shot"]),
    ("Zero-Shot Learning", ["Zero-Shot"]),
    ("Chain of Thought", ["CoT"]),
    ("Embeddings", ["Vector Embeddings"]),
    ("Attention Mechanism", ["Attention"]),
    ("Transformer", ["Transformer Architecture"]),
    ("Tokenization", ["Tokenizer"]),
    ("RLHF", ["Reinforcement Learning from Human Feedback"]),
    ("LoRA", ["Low-Rank Adaptation"]),
    ("Quantization", []),
    ("Distillation", ["Knowledge Distillation"]),
    ("Agentic AI", ["AI Agents"]),
    ("Tool Use", ["Function Calling"]),
    ("MCP", ["Model Context Protocol"]),
    ("Guardrails", ["AI Guardrails"]),
]


def generate_entries():
    """Generate all entries, deduplicated by name (case-sensitive)."""
    categories = [
        ("LANGUAGE", LANGUAGES),
        ("FRAMEWORK", FRAMEWORKS),
        ("DATABASE", DATABASES),
        ("TOOL", TOOLS),
        ("PLATFORM", PLATFORMS),
        ("AI_MODEL", AI_MODELS),
        ("ORGANIZATION", ORGANIZATIONS),
        ("SERVICE", SERVICES),
        ("PROTOCOL", PROTOCOLS),
        ("CONCEPT", CONCEPTS),
    ]

    seen = set()
    entries = []

    for label, items in categories:
        for primary, aliases in items:
            if primary not in seen:
                seen.add(primary)
                entries.append({
                    "name": primary,
                    "label": label,
                    "confidence": 0.99,
                    "frequency": 2,
                })
            for alias in aliases:
                if alias not in seen:
                    seen.add(alias)
                    entries.append({
                        "name": alias,
                        "label": label,
                        "confidence": 0.95,
                        "frequency": 2,
                    })

    return entries


def main():
    entries = generate_entries()
    for entry in entries:
        print(json.dumps(entry, ensure_ascii=False))
    print(f"# Total entries: {len(entries)}", file=sys.stderr)


if __name__ == "__main__":
    main()
